å§“å: å§“åï¼šå§“åï¼šAndroid CI

åœ¨â€¦â€¦ä¹‹ä¸Š:
æ¨:
åˆ†æ”¯æœºæ„: [åˆ†æ”¯æœºæ„ï¼š[åˆ†æ”¯æœºæ„ï¼š[ "ä¸»è¦" ]"ä¸»è¦" ][ "ä¸»è¦" ]"ä¸»è¦" ]
pull_request:
åˆ†æ”¯æœºæ„: [åˆ†æ”¯æœºæ„ï¼š[åˆ†æ”¯æœºæ„ï¼š[ "ä¸»è¦" ]"ä¸»è¦" ][ "ä¸»è¦" ]"ä¸»è¦" ]

å·¥ä½œ:
å»ºç«‹:
è¿ç»­çš„: è¿ç»­çš„ï¼šè¿ç»­çš„ï¼šUbuntu-æœ€æ–°:Ubuntu-æœ€æ–°
æƒé™:               # ğŸ‘ˆ æ˜¾å¼æˆæƒ
å†…å®¹: å†…å®¹: å†…å®¹: å†™: å†™

æ­¥éª¤:
      - uses: -usesï¼š-ä½¿ç”¨ï¼šæ“ä½œ/ç»“å¸@v4

      - å§“å: -å§“åï¼š-å§“åï¼šè®¾ç½®JDK17
uses: ç”¨é€”ï¼šç”¨é€”ï¼šæ“ä½œ/è®¾ç½®-Java@v4
å’Œâ€¦â€¦ä¸€èµ·:
javaç‰ˆ: '17'
åˆ†å¸ƒ: 'temurin'
ç¼“å­˜: ç¼“å­˜ï¼šç¼“å­˜ï¼šGradle

-å§“å: -å§“åï¼š-å§“åï¼šæˆäºˆgradlewçš„æ‰§è¡Œæƒé™
è·‘: è·‘ï¼šè·‘ï¼šchmod+x gradlew

      - å§“å: - å§“å: - å§“å: æ„å»ºç‰ˆæœ¬å®‰è£…åŒ…: æ„å»ºç‰ˆæœ¬å®‰è£…åŒ…
è·‘: è·‘ï¼šè·‘ï¼š./gradlewè£…é…é‡Šæ”¾

#åªåœ¨pushæ—¶å‘è¡Œï¼›PRæ—¶è·³è¿‡#åªåœ¨pushæ—¶å‘è¡Œï¼›PRæ—¶è·³è¿‡
      - å§“å: - å§“å: - å§“å: é‡Šæ”¾: é‡Šæ”¾
å¦‚æœ: å¦‚æœï¼šå¦‚æœï¼šgithub.event_name=='æ¨â€æ¨''æ¨''æ¨'
uses: ç”¨é€”ï¼šç”¨é€”ï¼šsoftrops/action-gh-release@v2
å’Œâ€¦â€¦ä¸€èµ·:
tag_name: æ ‡è®°åç§°(_N)ï¼šæ ‡è®°åç§°:v1.0.${{github.run_number}}{{github.run_number}}:v1.0.${{github.run_number}}{{github.run_number}}
å§“å: å§“åï¼šç‰ˆæœ¬v1.0.${{github.run_number}}{{github.run_number}}
æ–‡ä»¶: app/build/outputs/apk/release/app-release.apk
ç”Ÿæˆå‘å¸ƒæ³¨é‡Š: ç”Ÿæˆå‘å¸ƒæ³¨é‡Š: æ­£ç¡®
è‰æ¡ˆ: è‰æ¡ˆ: å‡çš„
é¢„å‘è¡Œ: é¢„å‘è¡Œ: å‡çš„
env:
GitHub_TOKEN: GitHub_TOKENï¼š${{secrets.GITHUB_TOKEN}}{{secrets.GITHUB_TOKEN}}
